# Generated by Django 5.2 on 2025-05-03 06:32

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a unique name for the genre.', max_length=100, unique=True)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier generated from the name.', max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
                'indexes': [models.Index(fields=['slug'], name='genre_slug_idx')],
            },
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movielens_id', models.CharField(blank=True, db_index=True, help_text='MovieLens identifier for the movie.', max_length=20, null=True, unique=True)),
                ('imdb_id', models.CharField(blank=True, db_index=True, help_text='IMDB identifier for the movie.', max_length=20, null=True)),
                ('tmdb_id', models.IntegerField(blank=True, help_text='TMDB identifier for the movie.', null=True)),
                ('title', models.CharField(help_text='The title of the movie.', max_length=255)),
                ('overview', models.TextField(blank=True, help_text='Brief description of the movie.')),
                ('release_date', models.DateField(blank=True, help_text='The release date of the movie.', null=True)),
                ('cast', models.JSONField(blank=True, help_text='List of main cast members as JSON array.', null=True)),
                ('language', models.CharField(blank=True, help_text='The primary language of the movie.', max_length=100)),
                ('poster_url', models.URLField(blank=True, db_index=True, help_text="URL to the movie's poster image.", null=True)),
                ('trailer_url', models.URLField(blank=True, help_text="URL to the movie's trailer.", null=True)),
                ('average_rating', models.DecimalField(db_index=True, decimal_places=2, default=0.0, help_text='Calculated average rating based on user reviews.', max_digits=4)),
                ('slug', models.SlugField(blank=True, help_text='URL-safe identifier generated from the title.', max_length=255, unique=True)),
                ('genres', models.ManyToManyField(help_text='Genres associated with this movie.', related_name='movies', to='recommendations.genre')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text="User's comment about the movie.")),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to=settings.AUTH_USER_MODEL)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='recommendations.movie')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Rating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.DecimalField(decimal_places=1, help_text="User's rating for the movie (0.0–5.0).", max_digits=3, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(5.0)])),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='recommendations.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Watchlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched', models.BooleanField(default=False, help_text='Whether the user has watched the movie.')),
                ('added_on', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlisted_by', to='recommendations.movie')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watchlist', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-added_on'],
            },
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['movielens_id'], name='movie_ml_id_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['slug'], name='movie_slug_idx'),
        ),
        migrations.AddIndex(
            model_name='comment',
            index=models.Index(fields=['movie', 'timestamp'], name='comment_movie_time_idx'),
        ),
        migrations.AddIndex(
            model_name='rating',
            index=models.Index(fields=['movie', 'score'], name='rating_movie_score_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'movie')},
        ),
        migrations.AddIndex(
            model_name='watchlist',
            index=models.Index(fields=['user', 'watched'], name='watchlist_user_watched_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='watchlist',
            unique_together={('user', 'movie')},
        ),
    ]
